motivational_sentences = [
    "In fin dei conti, una visione senza capacità di esecuzione è solo un’allucinazione.",
    "Prima o poi tutti dobbiamo soffrire una di queste due cose: il dolore della disciplina o il dolore del rimpianto.",
    "La visione senza esecuzione è solo un’allucinazione.",
    "L’investimento in conoscenza paga sempre i migliori interessi.",
    "Creati una visione talmente chiara da rendere tutte le tue paure irrilevanti.",
    "Determinazione: è lavorare duramente mentre si è già stanchi per il duro lavoro che si è già fatto.",
    "La più grande soddisfazione nella vita è riuscire a fare ciò che gli altri affermavano non saresti mai stato capace.",
    "Non è tanto il numero degli anni nella vita, bensì è la vita negli anni che conta.",
    "Se lanci il tuo prodotto e non ti senti in imbarazzo significa che lo hai lanciato troppo tardi.",
    "Non scambiare mai cosa vuoi ora con cosa vuoi di più.",
    "La vera chiave del successo è iniziare prima ancora di sentirsi completamente pronti.",
    "'Avere visione' è l’arte di vedere ciò che agli altri è invisibile.",
    "Tieniti gli amici vicini e i nemici ancora più vicini.",
    "Non importa quanto vai lento, l’importante è non fermarsi.",
    "I grandi avvenimenti del mondo hanno luogo nel cervello.",
    "L’ottimismo è un magnete della felicità. Se rimani positivo, le cose buone e le buone persone saranno attratte da te.",
    "Solo quando è abbastanza buio, si possono vedere le stelle.",
    "Ama i tuoi nemici perché essi tirano fuori il meglio di te.",
    "Il talento colpisce un bersaglio che nessun altro può colpire. Il genio colpisce un bersaglio che nessun altro può vedere.",
    "Il compito non è vedere quanto nessuno ha visto ancora, ma pensare quello che ancora nessuno ha pensato su ciò che tutti vedono.",
    "A volte non ottenere ciò che si vuole è un colpo di fortuna incredibile.",
    "L’esperienza mi ha insegnato che l’uomo quando desidera raggiungere un traguardo,trova dentro di sé risorse impensabili.",
    "Uno dei momenti più felici nella vita è quando trovi il coraggio di lasciare andare ciò che non puoi cambiare.",
    "A volte un vincitore è semplicemente un sognatore che non ha mai mollato.",
    "Devi aspettarti grandi cose da te stesso, prima ancora di farle.",
    "Non ho fallito. Ho solo pagato per delle lezioni.",
    "Sbagli il 100% dei colpi che non tiri.",
    "Non verrai mai pagato per avere delle idee. Verrai pagato per trasformarle in realtà.",
    "Lo scopo è quello di morire con tanti ricordi, non con tanti sogni.",
    "Almeno per oggi, ricordati che la tua vita non fa poi così schifo.",
    "Le difficoltà rafforzano la mente, così come il lavoro irrobustisce il corpo.",
]